### ISSUE TITLE
Lovely

### ISSUE THREAD

**Issue by AdrienLemaire** [jeanCarloMachado/vim-toop#1]
Thank you for this plugin, it's very useful.

Would it be possible to aggregate all useful shell and function mapping somewhere like the wiki ?
Having each map illustrated with a short explanation and example would make it that much faster to adopt (no need to search for the documentation of the underlying tool being used) for busy people.

Also, I'm afraid the number of shortcuts to remember is going to explode with this plugin. Do you have any tip to share for fast retrieval ? Would be cool to have mapping autocompletion (start all mappings by toop and search `,toop<tab>` to see the list of available maps).

**Comment by jeanCarloMachado** [comment]
Hey @Fandekasp thank you very much, it is by feedback like this that we feel the will to keep improving.

Agree, I'll create a document to explain usage. Actually if you want to start it (sending a PR)  feel free.

Regarding the explosion of shortcuts I dont have any magic bullet. I sometimes add them and later  remove the ones I did not use. But we can have a section about that on the wiki sharing strategies as well.

**Comment by jeanCarloMachado** [comment]
One strategy is to "namespace" them. Sharing the first letter when they have similar meaning.

```
call toop#mapShell('translate.sh en pt', 'tep')
call toop#mapShell('translate.sh pt en', 'tpe')
call toop#mapShell('translate.sh pt de', 'tpd')
call toop#mapShell('translate.sh en de', 'ted')
call toop#mapShell('translate.sh de en', 'tde')
call toop#mapShell('translate.sh de pt', 'tdp')
call toop#mapShell('translate.sh en fr', 'tef')
call toop#mapShell('translate.sh en la', 'tel')
call toop#mapShell('translate.sh la en', 'tle')
call toop#mapShell('translate.sh de en', '<leader>ge')
```

```
" debug {{{
let g:vdebug_keymap = {
\    "run" : "<leader>dr",
\    "run_to_cursor" : "<leader>du",
\    "step_over" : "<leader>dd",
\    "step_into" : "<leader>di",
\    "step_out" : "<leader>do",
\    "close" : "<leader>de",
\    "detach" : "<F7>",
\    "set_breakpoint" : "<leader>db",
\    "get_context" : "dx",
\    "eval_under_cursor" : "<F12>",
\    "eval_visual" : "<Leader>dv",
\}
```

**Comment by AdrienLemaire** [comment]
Thanks for making the wiki entry at https://github.com/jeanCarloMachado/vim-toop/wiki/usage-ideas

I'll use Anki to remember them.
To better remember the toop commands, my convention is to start all mappings with `<leader>t` to avoid confusion with other plugins (eg `<leader>c` for nerd commenter, `<leader>g` for gutentags etc)
