### ISSUE TITLE
toop vnoremap

### ISSUE THREAD

**Issue by AdrienLemaire** [jeanCarloMachado/vim-toop#2]
Hi @jeanCarloMachado 

Trying to make better use of vim-toop, but I'm often seeing other alternatives to do the same things.

For example, url encode/decode text :

without toop
```vim

vnoremap <leader>ue :!python3 -c 'import sys,urllib.parse;print(urllib.parse.quote(sys.stdin.read().strip()))'<cr>
vnoremap <leader>ud :!python3 -c 'import sys,urllib.parse;print(urllib.parse.unquote(sys.stdin.read().strip()))'<cr>
```

with toop:
```vim
" Toop Url Encode
call toop#mapShell('python3 -c "import sys,urllib.parse;print(urllib.parse.quote(sys.stdin.read().strip()))"', '<leader>tue')
" Toop Url Decode
call toop#mapShell('python3 -c "import sys,urllib.parse;print(urllib.parse.unquote(sys.stdin.read().strip()))"', '<leader>tud')
```

Is there some optimization done with toop? Can you highlight the differences between the 2 configurations?
Thank you for teaching me :)

**Comment by jeanCarloMachado** [comment]
Hello Fandekasp

Thank you for reaching out.
The difference between toop and the method you suggested is that toop allows you to bind the action with any text object.

Let's go to an example:

```
<a href="not escaped url">
```

Without vim toop your only solution is to select the "not scaped url" and then run the keystroke. With vim toop you can do something like: `<leader>tuei"` to encode inside the double quotes.
Toop's method is more declarative than imperative. You state the action do not perform it.

This is a trivial example but you can use all [vim text objects](https://blog.carbonfive.com/2011/10/17/vim-text-objects-the-definitive-guide/) with toop.


I hope this helps!

**Comment by AdrienLemaire** [comment]
Got it, thanks!
